# Generated by Django 6.0.4 on 2026-05-25 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0004_restaurant_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Master Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant')),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='categories.mastercategory')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('restaurant', 'master_category')},
            },
        ),
    ]
