# Generated by Django 6.0.4 on 2026-05-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('restaurants', '0007_restaurant_email_restaurant_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_categories', to='restaurants.restaurant'),
        ),
    ]
