# Generated by Django 6.0.4 on 2026-07-10 13:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_restaurant'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercategory',
            name='name',
        ),
        migrations.AddField(
            model_name='mastercategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 10, 13, 19, 4, 241725, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MasterCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language')),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.mastercategory')),
            ],
            options={
                'unique_together': {('master_category', 'language')},
            },
        ),
    ]
