# Generated by Django 6.0.4 on 2026-05-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurant_address_remove_restaurant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
