# Generated by Django 6.0.4 on 2026-07-24 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_types', '0001_initial'),
        ('restaurants', '0007_restaurant_email_restaurant_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='business_types.businesstype'),
        ),
    ]
