# Generated by Django 6.0.4 on 2026-05-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0003_alter_restaurant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(blank=True)),
                ('name_GR', models.CharField(max_length=255)),
                ('desc_GR', models.TextField(blank=True)),
                ('name_EN', models.CharField(max_length=255)),
                ('desc_EN', models.TextField(blank=True)),
                ('name_BG', models.CharField(blank=True, max_length=255)),
                ('desc_BG', models.TextField(blank=True)),
                ('name_RS', models.CharField(blank=True, max_length=255)),
                ('desc_RS', models.TextField(blank=True)),
                ('name_RO', models.CharField(blank=True, max_length=255)),
                ('desc_RO', models.TextField(blank=True)),
                ('name_DE', models.CharField(blank=True, max_length=255)),
                ('desc_DE', models.TextField(blank=True)),
                ('name_TR', models.CharField(blank=True, max_length=255)),
                ('desc_TR', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menus.menucategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
