# Generated by Django 6.0.4 on 2026-05-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Περιγραφή (English)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_gr',
            field=models.TextField(blank=True, default='', verbose_name='Περιγραφή (Ελληνικά)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Όνομα (English)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_gr',
            field=models.CharField(default='', max_length=255, verbose_name='Όνομα (Ελληνικά)'),
        ),
    ]
