# Generated by Django 6.0.4 on 2026-05-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_menuitem_description_remove_menuitem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description_gr',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_gr',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Όνομα'),
            preserve_default=False,
        ),
    ]
