# Generated by Django 6.0.4 on 2026-05-25 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('menus', '0003_remove_menuitem_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='categories.category'),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
