# Generated by Django 6.0.4 on 2026-07-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('menus', '0004_alter_menuitem_category_delete_menucategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Όνομα')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menus.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'language')},
            },
        ),
    ]
