# Generated by Django 6.0.4 on 2026-08-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_menuitem_description_remove_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
