# Generated by Django 6.0.4 on 2026-08-21 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('menus', '0007_allergen_menuitem_allergens'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menus.allergen')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language')),
            ],
            options={
                'unique_together': {('allergen', 'language')},
            },
        ),
    ]
