# Generated by Django 6.0.4 on 2026-07-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_remove_mastercategory_name_mastercategory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTypeMasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_categories', to='business_types.businesstype')),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_types', to='categories.mastercategory')),
            ],
            options={
                'unique_together': {('business_type', 'master_category')},
            },
        ),
    ]
